Dont catch NoClassDefFoundError as it will get reported as class not found which is misleading, not catching it means the actual exception does get thrown by a higher catch clause
git-svn-id: https://svn.apache.org/repos/asf/tuscany/sca-java-2.x/trunk@965814 13f79535-47bb-0310-9956-ffa450edef68