exclude cglib-full to prevent NoSuchMethodError due to version conflict
git-svn-id: https://svn.apache.org/repos/asf/incubator/tuscany/sandbox/jboynes/sca@415791 13f79535-47bb-0310-9956-ffa450edef68